	
CREATE TABLE T_ADMIN_DETAIL (
ADMIN_ID NUMERIC(9,0),
LOGIN_ID VARCHAR(50) NOT NULL,
CONSTRAINT PK_ADMIN_DETAIL PRIMARY KEY (ADMIN_ID)
);

CREATE SEQUENCE S_ADMIN_DETAIL INCREMENT BY 1 MAXVALUE 999999999 START WITH 1;


CREATE TABLE T_PROJECT_DETAIL (
PROJECT_ID NUMERIC(9,0),
PROJECT_NAME VARCHAR(100) NOT NULL,
REPO_URL VARCHAR(200),
CONSTRAINT PK_PROJECT_DETAIL PRIMARY KEY (PROJECT_ID)
);

CREATE SEQUENCE S_PROJECT_DETAIL INCREMENT BY 1 MAXVALUE 999999999 START WITH 1;

CREATE TABLE T_ATTESTATION_DETAIL ( 
ATTESTATION_ID NUMERIC(9,0),
EMP_ID VARCHAR(10) NOT NULL,
EMAIL VARCHAR(100) NOT NULL,
CONSTRAINT PK_ATTESTATION_DETAIL PRIMARY KEY (ATTESTATION_ID));

CREATE SEQUENCE S_ATTESTATION_DETAIL INCREMENT BY 1 MAXVALUE 999999999 START WITH 1;


CREATE TABLE T_ATTESTATION_AUDIT_REF (
ATTESTATION_AUD_REF_ID NUMERIC(9,0),
ATTESTATION_ID NUMERIC(9,0),
PROJECT_ID NUMERIC(9,0),
ATTESTATION_TIME TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
CONSTRAINT PK_ATT_AUDIT_REF PRIMARY KEY (ATTESTATION_AUD_REF_ID),
CONSTRAINT FK_ATT_AUDIT_DETAIL FOREIGN KEY (ATTESTATION_ID) REFERENCES T_ATTESTATION_DETAIL (ATTESTATION_ID),
CONSTRAINT FK_PROJECT_DETAIL FOREIGN KEY (PROJECT_ID) REFERENCES T_PROJECT_DETAIL (PROJECT_ID)
);

CREATE SEQUENCE S_ATTESTATION_AUD_REF INCREMENT BY 1 MAXVALUE 999999999 START WITH 1;

COMMIT;